# Generated by Django 5.0.9 on 2024-10-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_subscriptionprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={"ordering": ["order", "featured", "-updated"]},
        ),
    ]
